### ISSUE TITLE
When submit issues, got a error: Call to undefined function

### ISSUE THREAD

**Issue by ipfans** [FavioGalvis/Inforequest#15]
When I submit an issue to Mantisbt(AKA Inforequest), I got this error:

```
3168#0: *184461 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined function custom_function_override_issue_create_validate() in /home/wwwroot/bug/bug_report.php on line 199"
```

It seems that called a undefined function, and the page goto blank.

**Comment by FavioGalvis** [comment]
There is a custom function file not distributed, i have to fix that call but mean while you can use this file as a placeholder.

Just download it, and put in in ...Inforequest/config/

https://drive.google.com/file/d/0B6tgZa6-4QV-N25kMVBkekU1NXM/view?usp=sharing

**Comment by FavioGalvis** [comment]
If you have any other problems, feel free to reopen this issue or opening another one.
